### ISSUE TITLE
how to get depth map?

### ISSUE THREAD

**Issue by liushifu12138** [TruongKhang/cds-mvsnet#10]

**Comment by TruongKhang** [comment]
when you run file `test.py`, it automatically saves the depth maps for you. It is saved in the format of `.pfm` file which can be loaded by the function in file `datasets/data_io.py`. If you want to save the depth maps in `.png` format, you can simply modify the code in test.py!!!

**Comment by TruongKhang** [comment]
@liushifu12138 , if you don't have any questions, I just close this issue here! Thanks
