### ISSUE TITLE
Evaluate the results

### ISSUE THREAD

**Issue by zhang-snowy** [TruongKhang/cds-mvsnet#11]
Hello, author. The result of reconstruction of DTU model in prepareed provided by you is not satisfactory. I also set prob_threshold. What is the reason?

python test.py --dataset dtu --batch_size 1 --testpath $TESTPATH --testlist $TESTLIST --resume $CKPT_FILE --outdir $OUTDIR --interval_scale 1.06 --num_view 5 --numdepth 192 --max_h 1152 --max_w 1536 --filter_method gipuma --disp_threshold 0.1 --num_consistent 2 --prob_threshold 0.19
![git](https://user-images.githubusercontent.com/71815049/165124753-10d04e1a-3f48-4d1e-bd9a-6ba6b72dd137.png)

**Comment by TruongKhang** [comment]
@zhang-snowy, which pre-trained model did you use? You can remove `prob_threshold`, it does not affect much in DTU. Also, I uploaded the 3D reconstructed models for DTU in (README)[https://github.com/TruongKhang/cds-mvsnet/blob/main/README.md]. If you find your reconstructed models similarly, then they would be exactly our results!

**Comment by zhang-snowy** [comment]
@TruongKhang Thank you very much for your reply, I use your CDS - mvsnet/tree/main/pretrained under the training model of fusion

**Comment by TruongKhang** [comment]
@zhang-snowy, then your produced result is reasonable. As I explained above, the scene 77 is hard to reconstruct completely because of large untextured scenes. Actually, if you run the Matlab evaluation code, this scene also gave a lowest evaluated metrics. 
And just one small thing, if you like our repo, please give me 1 star :D

**Comment by zhang-snowy** [comment]
OK ! ! ! Thank you very much for your reply ! ! !  : D
