### ISSUE TITLE
pretrained check point file required.

### ISSUE THREAD

**Issue by taohu1994** [TruongKhang/cds-mvsnet#15]
Hi, thanks for your wonderful job. Could you upload the pretrained DTU check point file? It helps a lot for rapid evaluation. Thanks.

**Comment by TruongKhang** [comment]
Hi @taohu1994 , all pretrained models are available [here](https://github.com/TruongKhang/cds-mvsnet/tree/main/pretrained)

**Comment by taohu1994** [comment]
thanks, I test the dtu dataset, it outputs great result. While when I use my own dataset, the result is quite poor. It likes 
<img width="557" alt="screen_shot" src="https://user-images.githubusercontent.com/26554614/185549771-f378351e-da15-4fdc-b59b-e17e06d1c58f.png">

Do you have any idea why this happened? Thank you.

**Comment by TruongKhang** [comment]
@taohu1994, maybe the problem is from data preprocessing. 
How did you prepare your images and camera poses?
Did you follow [these instructions](https://github.com/TruongKhang/cds-mvsnet#some-notes-about-preparation-to-test-on-your-custom-datasets)?
