### ISSUE TITLE
 fine-tuning on BlendedMVS

### ISSUE THREAD

**Issue by liubowen1233** [TruongKhang/cds-mvsnet#16]
hello. thank you for sharing this wonderful research result.
I'm having some problems in  fine-tuning on BlendedMVS and Training on DTU and BlendedMVS simultaneously.
To train model on DTU dataset is fine，After the training is finished，fine-tuning on BlendedMVS，TypeError: __init__() got an unexpected keyword argument 'pretrained'.
![image](https://user-images.githubusercontent.com/98573184/198262520-c56ab8ee-9932-4027-b207-a022a8dce236.png)
in Training on DTU and BlendedMVS simultaneously，AttributeError: module 'models.model' has no attribute 'TAMVSNet'.
I can't find where TAMVSNet is defined.

**Comment by TruongKhang** [comment]
@liubowen1233, I changed the method name after releasing the code. 
So, you only need to change TAMVSNet --> CDSMVSNet.
I updated the [config_all_dataset.json](https://github.com/TruongKhang/cds-mvsnet/blob/main/configs/config_all_dataset.json) file for your reference.
If you have any problems, please let me know!!!

**Comment by liubowen1233** [comment]
Thank you very much for your answer!
