### ISSUE TITLE
Problem with demo

### ISSUE THREAD

**Issue by denred0** [TruongKhang/cds-mvsnet#17]
I tried [this demo](https://github.com/TruongKhang/DROID-SLAM) and got strange results. 
I set the environment and installed all libs.
Start the demo with the comand:
`python demo.py --imagedir=data/nmail6 --calib=calib/nmail3.txt --stride=2 --buffer 384 --mvsnet_ckpt cds_mvsnet.pth --disable_vis
` 
After frame 23 processing stops. I found out that this line is the source of the error:
DROID-SLAM\droid_slam\geom\projective_ops.py
```
# transform
Gij = poses[:,jj] * poses[:,ii].inv()
```
Since the determinant of the matrix `poses` is equal to zero, the operation `inv()` cannot be performed. 
It looks like poses not updated. 

Do you know where is can be problem? 
Thank you.

**Comment by TruongKhang** [comment]
Hi @denred0, it looks like from the `DROID-SLAM` code. Unfortunately, I didn't dig into this code in detail so I'm not sure. 
But I ran the demo and there was no problem at all. Can you share a screenshot of your errors came out? 
And how much is your GPU memory?

**Comment by denred0** [comment]
Hi @TruongKhang, thanks for quick response. I got error `Process finished with exit code -1073741819 (0xC0000005)`. I have only 4Gb of GPU on my laptop and think this error can be connected with small amount of GPU memory. Today I want to test code on Colab to prove my theory about small amount of GPU memory.

**Comment by TruongKhang** [comment]
Oh, I see. I think you should use a GPU of at least 8 GB. Or, you can try to reduce the [image_size](https://github.com/TruongKhang/DROID-SLAM/blob/main/demo.py#L70) to test on your current GPU.

**Comment by denred0** [comment]
I tried to reduce the image_size but got error:
`The expanded size of the tensor (224) must match the existing size (448) at non-singleton dimension 2.  Target sizes: [3, 128, 224].  Tensor sizes: [3, 256, 448]`

Probably it is necessary to somehow change the code to make it work.

**Comment by TruongKhang** [comment]
humm, I see. So please let me know the result when you try on Google Colab! :D

**Comment by denred0** [comment]
As a result, I was able to run the demo in the colab. The code consumes 15Gb RAM during installation and 5.5Gb GPU during inference.
Thanks for your help.
