### ISSUE TITLE
question about scale selection 

### ISSUE THREAD

**Issue by maybeLx** [TruongKhang/cds-mvsnet#18]
Dear author,  It is really excellent work in MVS. But during reading your paper, I have some misunderstanding about your paper Figure1, fig (a) shows  many scale selections for pixels in different resolution images, however you only have 3 5 7 11 kernel size to choose, I have no idea about the scale 17.

**Comment by TruongKhang** [comment]
Hi @maybeLx , that's a good question. 
If I remember correctly, to draw Figure 1a, I computed roughly the scales after stacking several CDSConv layers. So, Figure 1a does not show the estimated scales using only one CDSConv layer. During the experiments, I tried options for choosing the scale candidates for each CDSConv layer. So, I think Figure 1a was drawn after applying 2 CDSConv layers in [line 211, 212](https://github.com/TruongKhang/cds-mvsnet/blob/main/models/module.py#L212), but the scale candidates might not be the same.  

Please read the last paragraph of Section 3.3. We explained that "**To have a low computational complexity, the number of candidate scales in CDSConv layer should be small, we only use 2 or 3 candidates. However, the searching scale-space is expanded profoundly when multiple CDSConv layers are stacked in CDSFNet**".

I hope this will answer your concern. Please let me know if you have more questions!

**Comment by maybeLx** [comment]
Thanks, I understand
