### ISSUE TITLE
tank and temples scores

### ISSUE THREAD

**Issue by ajunyo** [TruongKhang/cds-mvsnet#4]
nice work!
I'd like to ask how the parameters of tank should be set . In fact, I can get a good result on DTU when doing experiments, but not on tank, or even very poor

**Comment by TruongKhang** [comment]
Hello @ajunyo, did you use my [script](https://github.com/TruongKhang/cds-mvsnet/tree/main/scripts) to reproduce the result on Tanks and Temples?

**Comment by ajunyo** [comment]
I uploaded it with the default script. Thank you for your answer. It's really a good job
