### ISSUE TITLE
num_worker?

### ISSUE THREAD

**Issue by lilipopololo** [TruongKhang/cds-mvsnet#6]
Hello author, I would like to ask how to change number of num_workers in Dataloader
I can't find any code about "num_workers " in this project,maybe you set num_workers ==0 for stability?

**Comment by lilipopololo** [comment]
As i find in configs/config_dtu.json, key "dataloader" in configure file is a list, should i copy  the item in this list to set  num_workers ?
https://github.com/TruongKhang/cds-mvsnet/blob/ec78358a1503728309299bbfdacc432942557712/configs/config_dtu.json#L16

**Comment by TruongKhang** [comment]
hiiii @lilipopololo, I fixed the num_workers = 4 in the file [dataloaders.py](https://github.com/TruongKhang/cds-mvsnet/blob/main/datasets/data_loaders.py). 
Yes, you can add the parameters `num_workers` to the file `config_dtu.json` and then add an initial variable `num_workers` in `__init__` function of DTULoader.

**Comment by lilipopololo** [comment]
I see thank you
