### ISSUE TITLE
tank

### ISSUE THREAD

**Issue by liushifu12138** [TruongKhang/cds-mvsnet#7]
Reading disp 151
Resizing globalstate to 152
Killed
cp: 无法获取'tt_outputs/Family/points_mvsnet/con*/final3d_model.ply' 的文件状态(stat): 没有那个文件或目录

**Comment by TruongKhang** [comment]
How much is your GPU memory? Did you follow the installation in [README](https://github.com/TruongKhang/cds-mvsnet/blob/main/README.md)?

**Comment by liushifu12138** [comment]
GPU=15G

**Comment by liushifu12138** [comment]
how to use short_range_cameras

**Comment by TruongKhang** [comment]
> GPU=15G

I think you need more GPU. at least 24GB




> how to use short_range_cameras

This is provided by [Yao Yao-MVSNet](https://drive.google.com/file/d/1YArOJaX9WVLJh4757uE8AEREYkgszrCo/view)
