### ISSUE TITLE
aggregated cost V

### ISSUE THREAD

**Issue by zhang-snowy** [TruongKhang/cds-mvsnet#8]
Why aggregated cost V（Cost V olume Formulation）, as in the paper? Does it mean anything?

**Comment by TruongKhang** [comment]
Hi @zhang-snowy, please take a look at our paper. Also, we recommend you a list of earlier works that use this concept, including VisMVSNet, PVSNet, or PatchMatchNet.
I can simply explain as follows. First, we compute a two-view matching cost volume for each pair (reference image, source image). Then all two-view cost volumes from all pairs of reference-source image are integrated into a single volume V by using the weighted mean operation. Estimating the cost volume V is a common step in the multi-view stereo problem

**Comment by zhang-snowy** [comment]
Thank u : ) ！！！
