### ISSUE TITLE
It doesn't work well for my custom datasets.

### ISSUE THREAD

**Issue by bring728** [TruongKhang/cds-mvsnet#9]
First of all, thank you for sharing your great research.

I have 9 images and the cameras are all facing the same direction. I want to get 9 depth maps.
For the DTU dataset, depth estimation works fine with your network.
But when I input my image, I get the following bad result.
![스크린샷, 2022-04-20 19-28-04](https://user-images.githubusercontent.com/24850969/164211630-1548420e-936a-4d09-8eb2-358f0bb4569a.png)
![스크린샷, 2022-04-20 19-27-53](https://user-images.githubusercontent.com/24850969/164211640-8ba05c4b-bff7-4688-ad3a-c64de9df914b.png)
![스크린샷, 2022-04-20 19-27-35](https://user-images.githubusercontent.com/24850969/164211646-63d9c95c-f38b-42d2-8a3b-fcc6113bfb20.png)

I don't know if it has anything to do with it, but the camera coordinate system I used is right, down, forward. And with depth_min = 1.25 I set depth_inverval=0.1.
In the case of num_view, it is set to 9 so that all images are always used.

Do you have any guesses why?

**Comment by bring728** [comment]
Oh, I made a mistake. There was a part where the intrinsics matrix was divided by 4, but I omitted it. I solved it, and the result is good to some extent.

**Comment by zhang-snowy** [comment]
> 

How did you solve this problem? I had a similar problem......
